/**
 * Autogenerated file. Don't change it manualy.
 */

/** -------------------- models -------------------- */

/** auth */
const AuthGroup = require("./auth/db/models/group");
const AuthGroupuser = require("./auth/db/models/groupuser");
const AuthRolerule = require("./auth/db/models/rolerule");
const AuthUattribute = require("./auth/db/models/uattribute");
const AuthUrole = require("./auth/db/models/urole");
const AuthUrule = require("./auth/db/models/urule");
const AuthUser = require("./auth/db/models/user");
const AuthUserdata = require("./auth/db/models/userdata");
const AuthUserinfo = require("./auth/db/models/userinfo");
const AuthUserrole = require("./auth/db/models/userrole");
const AuthUserrule = require("./auth/db/models/userrule");
/** dump-cms */
const DumpCmsDumpmeta = require("./dump-cms/db/models/dumpmeta");
/** metadata-cmp */
const MetadataCmpFamilymetadata = require("./metadata-cmp/db/models/familymetadata");
const MetadataCmpMetadata = require("./metadata-cmp/db/models/metadata");
/** i-l-init */
const ILInitRuntimeConfig = require("./i-l-init/db/models/RuntimeConfig");
/** meta-query-explain */
const MetaQueryExplainExplainRequest = require("./meta-query-explain/db/models/ExplainRequest");
const MetaQueryExplainExplainRequestMeta = require("./meta-query-explain/db/models/ExplainRequestMeta");
/** meta-synh-dbmodel */
const MetaSynhDbmodelMetadatadb = require("./meta-synh-dbmodel/db/models/metadatadb");
/** metadata-processing */
const MetadataProcessingProcessing = require("./metadata-processing/db/models/processing");
/** code-manager */
const CodeManagerCode = require("./code-manager/db/models/Code");
/** schemas-manager */
const SchemasManagerSchemaManager = require("./schemas-manager/db/models/SchemaManager");
/** pivot-table */
const PivotTablePivotSchemas = require("./pivot-table/db/models/PivotSchemas");
/** rls-ext-metadata */
const RlsExtMetadataRlsmetadata = require("./rls-ext-metadata/db/models/rlsmetadata");
/** store */
const StoreStore = require("./store/db/models/store");
/** system-settings */
const SystemSettingsSystemSettings = require("./system-settings/db/models/SystemSettings");
/** template-cms */
const TemplateCmsFamilytemplate = require("./template-cms/db/models/familytemplate");
const TemplateCmsParamstype = require("./template-cms/db/models/paramstype");
const TemplateCmsTemplate = require("./template-cms/db/models/template");
const TemplateCmsTemplateparam = require("./template-cms/db/models/templateparam");
/** page-cms */
const PageCmsFamilypage = require("./page-cms/db/models/familypage");
const PageCmsPageparam = require("./page-cms/db/models/pageparam");
const PageCmsPages = require("./page-cms/db/models/pages");

module.exports = {
    "adminpanel-dumps": [],
    "analytics-ext-metadata-cmp": [],
    "middleware-rest-upload-file": [],
    "middleware-rest-validate": [],
    "middleware-rest-check-access": [],
    "auth": [
        AuthGroup,
        AuthGroupuser,
        AuthRolerule,
        AuthUattribute,
        AuthUrole,
        AuthUrule,
        AuthUser,
        AuthUserdata,
        AuthUserinfo,
        AuthUserrole,
        AuthUserrule
    ],
    "cached": [],
    "statistics-agent": [],
    "compression": [],
    "cors-ext-rest-express": [],
    "csv-parser": [],
    "dump-cms": [
        DumpCmsDumpmeta
    ],
    "error-stack-trace": [],
    "utils": [],
    "metadata-cmp": [
        MetadataCmpFamilymetadata,
        MetadataCmpMetadata
    ],
    "middleware-rest-in-transaction": [],
    "middleware-rest-check-auth": [],
    "query-builder": [],
    "metadata-connector": [],
    "metadata-logic": [],
    "metadata-infoservice-guide": [],
    "metadata-infoservice": [],
    "meta-aggregate-calc-field": [],
    "meta-where-formatter": [],
    "metadata-processing-query": [],
    "metadata-cubes-query": [],
    "metadata-cubes": [],
    "i-l-init": [
        ILInitRuntimeConfig
    ],
    "i-woke-up": [],
    "itable-ext-metadata": [],
    "json-body-ext-rest-express": [],
    "logger-mis": [],
    "memorysave-ext-helpers": [],
    "memorysave-metadata": [],
    "memorysave-storage-node-cache": [],
    "memorysave-storage-redis": [],
    "meta-copy-infofields": [],
    "meta-copy-paste": [],
    "meta-cube-info": [],
    "meta-ddl-dump": [],
    "meta-dumpdb": [],
    "meta-filter": [],
    "meta-fsck-lib": [],
    "meta-fsck": [],
    "wrapper": [],
    "meta-new-cube-page": [],
    "meta-query-explain": [
        MetaQueryExplainExplainRequest,
        MetaQueryExplainExplainRequestMeta
    ],
    "meta-search": [],
    "meta-sql-query": [],
    "meta-synh-dbmodel": [
        MetaSynhDbmodelMetadatadb
    ],
    "metadata-enums": [],
    "metadata-forms": [],
    "metadata-gp-timeout": [],
    "metadata-cmp-dumps": [],
    "metadata-infoservice-matrixguide": [],
    "metadata-loger": [],
    "metadata-processing": [
        MetadataProcessingProcessing
    ],
    "worker_code": [],
    "metadata-reports": [],
    "metadata-roles": [],
    "metadata-rules": [],
    "metadata-users": [],
    "metadata-rls": [],
    "middleware-rest-cors": [],
    "middleware-rest-decimal": [],
    "middleware-rest-validator": [],
    "rls-core": [],
    "code-manager": [
        CodeManagerCode
    ],
    "Application": [],
    "meta-object-server-code": [],
    "QueueAgent": [],
    "TransactionAgent": [],
    "metadata-guide": [],
    "schemas-manager": [
        SchemasManagerSchemaManager
    ],
    "mis-portal-ext-schemas-manager": [],
    "parse-dbmodel-meta": [],
    "pivot-table": [
        PivotTablePivotSchemas
    ],
    "reports": [],
    "reports-xlsx-download": [],
    "rest-express": [],
    "rls-ext-metadata": [
        RlsExtMetadataRlsmetadata
    ],
    "rls-ext-metadata-dumps": [],
    "rls-ext-sync": [],
    "rls-ui": [],
    "session-set": [],
    "store": [
        StoreStore
    ],
    "system-settings": [
        SystemSettingsSystemSettings
    ],
    "system-settings-ext-analytics": [],
    "user-device": [],
    "secman": [],
    "meta-muilti-field": [],
    "postgres-ext-query-builder": [],
    "connector-postgres": [],
    "metadata-forms-dumps": [],
    "metadata-templates-dumps": [],
    "meta-eye": [],
    "meta-matrix": [],
    "template-cms": [
        TemplateCmsFamilytemplate,
        TemplateCmsParamstype,
        TemplateCmsTemplate,
        TemplateCmsTemplateparam
    ],
    "page-cms": [
        PageCmsFamilypage,
        PageCmsPageparam,
        PageCmsPages
    ],
};
