/**
 * Autogenerated file. Don't change it manualy.
 */

/** auth */
const AuthAuthRouter = require("./auth/routers/Auth.router");
const AuthUsersUiRouter = require("./auth/routers/UsersUi.router");
/** cached */
const CachedAppendCache = require("./cached/middleware/appendCache");
/** statistics-agent */
const StatisticsAgentLoggerMiddleware = require("./statistics-agent/middleware/loggerMiddleware");
/** compression */
const CompressionCompressionMiddleware = require("./compression/middleware/compression.middleware");
/** cors-ext-rest-express */
const CorsExtRestExpressCors = require("./cors-ext-rest-express/middleware/cors");
/** dump-cms */
const DumpCmsDumpDBRouter = require("./dump-cms/routers/DumpDB.router");
/** metadata-cmp */
const MetadataCmpMetadataRouter = require("./metadata-cmp/routers/Metadata.router");
const MetadataCmpMetadataV2Router = require("./metadata-cmp/routers/MetadataV2.router");
const MetadataCmpMetadataV3Router = require("./metadata-cmp/routers/MetadataV3.router");
/** metadata-connector */
const MetadataConnectorConnectorsRouter = require("./metadata-connector/routers/Connectors.router");
/** metadata-infoservice-guide */
const MetadataInfoserviceGuideFieldsRouter = require("./metadata-infoservice-guide/routers/Fields.router");
const MetadataInfoserviceGuideFieldsListRouter = require("./metadata-infoservice-guide/routers/FieldsList.router");
const MetadataInfoserviceGuideIndexesRouter = require("./metadata-infoservice-guide/routers/Indexes.router");
const MetadataInfoserviceGuideKeysRouter = require("./metadata-infoservice-guide/routers/Keys.router");
const MetadataInfoserviceGuideInfoservicesRouter = require("./metadata-infoservice-guide/routers/Infoservices.router");
/** metadata-infoservice */
const MetadataInfoserviceFieldsRouter = require("./metadata-infoservice/routers/Fields.router");
const MetadataInfoserviceFieldsListRouter = require("./metadata-infoservice/routers/FieldsList.router");
const MetadataInfoserviceIndexesRouter = require("./metadata-infoservice/routers/Indexes.router");
const MetadataInfoserviceKeysRouter = require("./metadata-infoservice/routers/Keys.router");
const MetadataInfoserviceForeignKeysRouter = require("./metadata-infoservice/routers/ForeignKeys.router");
const MetadataInfoserviceInfoservicesRouter = require("./metadata-infoservice/routers/Infoservices.router");
/** metadata-cubes */
const MetadataCubesMeasuresAggregationsRouter = require("./metadata-cubes/routers/MeasuresAggregations.router");
const MetadataCubesFieldsAggregationsRouter = require("./metadata-cubes/routers/FieldsAggregations.router");
const MetadataCubesInfoservicesRouter = require("./metadata-cubes/routers/Infoservices.router");
const MetadataCubesFieldsRouter = require("./metadata-cubes/routers/Fields.router");
const MetadataCubesMeasuresRouter = require("./metadata-cubes/routers/Measures.router");
const MetadataCubesDimensionsRouter = require("./metadata-cubes/routers/Dimensions.router");
const MetadataCubesFieldsListRouter = require("./metadata-cubes/routers/FieldsList.router");
const MetadataCubesFizFieldsListRouter = require("./metadata-cubes/routers/FizFieldsList.router");
const MetadataCubesInfoserviseListRouter = require("./metadata-cubes/routers/InfoserviseList.router");
const MetadataCubesBindsRouter = require("./metadata-cubes/routers/Binds.router");
const MetadataCubesCubesRouter = require("./metadata-cubes/routers/Cubes.router");
/** i-woke-up */
const IWokeUpIWokeUp = require("./i-woke-up/middleware/iWokeUp");
/** json-body-ext-rest-express */
const JsonBodyExtRestExpressJsonBody = require("./json-body-ext-rest-express/middleware/jsonBody");
/** logger-mis */
const LoggerMisLoggerMiddleware = require("./logger-mis/middleware/loggerMiddleware");
/** memorysave-metadata */
const MemorysaveMetadataMemorySaveMetadataRouter = require("./memorysave-metadata/routers/MemorySaveMetadata.router");
/** meta-copy-infofields */
const MetaCopyInfofieldsMetaCopyInfofieldsRouter = require("./meta-copy-infofields/routers/metaCopyInfofields.router");
/** meta-copy-paste */
const MetaCopyPasteMetaCopyPasteRouter = require("./meta-copy-paste/routers/metaCopyPaste.router");
/** meta-ddl-dump */
const MetaDdlDumpMetaDDLDumpRouter = require("./meta-ddl-dump/routers/MetaDDLDump.router");
/** meta-dumpdb */
const MetaDumpdbMetaDumpDBRouter = require("./meta-dumpdb/routers/metaDumpDB.router");
/** meta-filter */
const MetaFilterFilterRouter = require("./meta-filter/routers/Filter.router");
/** meta-fsck */
const MetaFsckMetaFSCKRouter = require("./meta-fsck/routers/MetaFSCK.router");
/** wrapper */
const WrapperWrapperRouter = require("./wrapper/routers/wrapper.router");
/** meta-new-cube-page */
const MetaNewCubePageMetaNewCubePageRouter = require("./meta-new-cube-page/routers/metaNewCubePage.router");
const MetaNewCubePageMetaNewReportPageRouter = require("./meta-new-cube-page/routers/metaNewReportPage.router");
/** meta-query-explain */
const MetaQueryExplainMetaQueryExplainRouter = require("./meta-query-explain/routers/MetaQueryExplain.router");
/** meta-search */
const MetaSearchMetaSearchRouter = require("./meta-search/routers/MetaSearch.router");
/** meta-sql-query */
const MetaSqlQueryMetaSQLQueryRouter = require("./meta-sql-query/routers/metaSQLQuery.router");
/** meta-synh-dbmodel */
const MetaSynhDbmodelMetaSynhDbmodelRouter = require("./meta-synh-dbmodel/routers/metaSynhDbmodel.router");
/** metadata-enums */
const MetadataEnumsValuesRouter = require("./metadata-enums/routers/Values.router");
const MetadataEnumsEnumsRouter = require("./metadata-enums/routers/Enums.router");
/** metadata-forms */
const MetadataFormsFormsRouter = require("./metadata-forms/routers/Forms.router");
/** metadata-infoservice-matrixguide */
const MetadataInfoserviceMatrixguideHierarchyRouter = require("./metadata-infoservice-matrixguide/routers/Hierarchy.router");
const MetadataInfoserviceMatrixguideSysFieldsRouter = require("./metadata-infoservice-matrixguide/routers/SysFields.router");
const MetadataInfoserviceMatrixguideFieldsRouter = require("./metadata-infoservice-matrixguide/routers/Fields.router");
const MetadataInfoserviceMatrixguideFieldsListRouter = require("./metadata-infoservice-matrixguide/routers/FieldsList.router");
const MetadataInfoserviceMatrixguideKeysRouter = require("./metadata-infoservice-matrixguide/routers/Keys.router");
const MetadataInfoserviceMatrixguideInfoserviceMatrixGuideRouter = require("./metadata-infoservice-matrixguide/routers/InfoserviceMatrixGuide.router");
/** metadata-processing */
const MetadataProcessingAggregationsRouter = require("./metadata-processing/routers/Aggregations.router");
const MetadataProcessingMeasuresRouter = require("./metadata-processing/routers/Measures.router");
const MetadataProcessingMatrixRouter = require("./metadata-processing/routers/Matrix.router");
const MetadataProcessingDimensionsRouter = require("./metadata-processing/routers/Dimensions.router");
const MetadataProcessingProcessingRouter = require("./metadata-processing/routers/Processing.router");
const MetadataProcessingCalculationRouter = require("./metadata-processing/routers/Calculation.router");
/** metadata-reports */
const MetadataReportsInfoservicesRouter = require("./metadata-reports/routers/Infoservices.router");
const MetadataReportsMeasuresRouter = require("./metadata-reports/routers/Measures.router");
const MetadataReportsDimensionsRouter = require("./metadata-reports/routers/Dimensions.router");
const MetadataReportsInfoserviseListRouter = require("./metadata-reports/routers/InfoserviseList.router");
const MetadataReportsReportsRouter = require("./metadata-reports/routers/Reports.router");
const MetadataReportsFieldsListRouter = require("./metadata-reports/routers/FieldsList.router");
const MetadataReportsFizFieldsListRouter = require("./metadata-reports/routers/FizFieldsList.router");
const MetadataReportsFieldsRouter = require("./metadata-reports/routers/Fields.router");
/** metadata-roles */
const MetadataRolesRolesRouter = require("./metadata-roles/routers/Roles.router");
/** metadata-rules */
const MetadataRulesRulesRouter = require("./metadata-rules/routers/Rules.router");
/** metadata-users */
const MetadataUsersUsersRouter = require("./metadata-users/routers/Users.router");
/** metadata-rls */
const MetadataRlsConditionRouter = require("./metadata-rls/routers/Condition.router");
const MetadataRlsRlsRouter = require("./metadata-rls/routers/Rls.router");
/** rls-core */
const RlsCoreRlsCoreRouter = require("./rls-core/routers/RlsCore.router");
/** code-manager */
const CodeManagerCodeRouter = require("./code-manager/routers/code.router");
/** metadata-guide */
const MetadataGuideFieldsRouter = require("./metadata-guide/routers/Fields.router");
const MetadataGuideFieldsListRouter = require("./metadata-guide/routers/FieldsList.router");
const MetadataGuideTabularPartsRouter = require("./metadata-guide/routers/TabularParts.router");
const MetadataGuideTabularFieldsListRouter = require("./metadata-guide/routers/TabularFieldsList.router");
const MetadataGuideFormsRouter = require("./metadata-guide/routers/Forms.router");
const MetadataGuideSysFieldsRouter = require("./metadata-guide/routers/SysFields.router");
const MetadataGuideTabularSysFieldsRouter = require("./metadata-guide/routers/TabularSysFields.router");
const MetadataGuideIndexesRouter = require("./metadata-guide/routers/Indexes.router");
const MetadataGuideKeysRouter = require("./metadata-guide/routers/Keys.router");
const MetadataGuideGuideRouter = require("./metadata-guide/routers/Guide.router");
/** schemas-manager */
const SchemasManagerSchemasManagerRouter = require("./schemas-manager/routers/SchemasManager.router");
/** parse-dbmodel-meta */
const ParseDbmodelMetaParseDbmodelMetaRouter = require("./parse-dbmodel-meta/routers/parseDbmodelMeta.router");
/** pivot-table */
const PivotTablePivotTableRouter = require("./pivot-table/routers/PivotTable.router");
/** reports */
const ReportsReportsRouter = require("./reports/routers/Reports.router");
/** reports-xlsx-download */
const ReportsXlsxDownloadReportsXlsxDownloadRouter = require("./reports-xlsx-download/routers/ReportsXlsxDownload.router");
/** rls-ext-metadata */
const RlsExtMetadataRlsExtMetadataRouter = require("./rls-ext-metadata/routers/RlsExtMetadata.router");
/** rls-ui */
const RlsUiRlsUIRouter = require("./rls-ui/routers/RlsUI.router");
/** session-set */
const SessionSetAppendSessionParser = require("./session-set/middleware/appendSessionParser");
const SessionSetCreateMainSession = require("./session-set/middleware/createMainSession");
const SessionSetCreateUserSession = require("./session-set/middleware/createUserSession");
/** session-set */
const SessionSetSessionSetRouter = require("./session-set/routers/SessionSet.router");
/** store */
const StoreAppendUserData = require("./store/middleware/appendUserData");
/** store */
const StoreStoreRouter = require("./store/routers/Store.router");
/** system-settings */
const SystemSettingsSystemSettingsRouter = require("./system-settings/routers/SystemSettings.router");
/** user-device */
const UserDeviceDeviceRouter = require("./user-device/routers/Device.router");
/** meta-muilti-field */
const MetaMuiltiFieldMetaCompositeHelperRouter = require("./meta-muilti-field/routers/MetaCompositeHelper.router");
/** meta-eye */
const MetaEyeMetaEyeRouter = require("./meta-eye/routers/metaEye.router");
/** meta-matrix */
const MetaMatrixMetaMatrixRouter = require("./meta-matrix/routers/metaMatrix.router");
/** template-cms */
const TemplateCmsTemplatesRouter = require("./template-cms/routers/Templates.router");
/** page-cms */
const PageCmsPagesRouter = require("./page-cms/routers/Pages.router");
const PageCmsPagesUiRouter = require("./page-cms/routers/PagesUi.router");

module.exports = {
    "adminpanel-dumps": {
        middlewares: [],
        routers: {},
    },
    "analytics-ext-metadata-cmp": {
        middlewares: [],
        routers: {},
    },
    "middleware-rest-upload-file": {
        middlewares: [],
        routers: {},
    },
    "middleware-rest-validate": {
        middlewares: [],
        routers: {},
    },
    "middleware-rest-check-access": {
        middlewares: [],
        routers: {},
    },
    "auth": {
        middlewares: [],
        routers: {
            "/auth": AuthAuthRouter,
            "/usersui": AuthUsersUiRouter
        },
    },
    "cached": {
        middlewares: [
            CachedAppendCache
        ],
        routers: {},
    },
    "statistics-agent": {
        middlewares: [
            StatisticsAgentLoggerMiddleware
        ],
        routers: {},
    },
    "compression": {
        middlewares: [
            CompressionCompressionMiddleware
        ],
        routers: {},
    },
    "cors-ext-rest-express": {
        middlewares: [
            CorsExtRestExpressCors
        ],
        routers: {},
    },
    "csv-parser": {
        middlewares: [],
        routers: {},
    },
    "dump-cms": {
        middlewares: [],
        routers: {
            "/dumpdb": DumpCmsDumpDBRouter
        },
    },
    "error-stack-trace": {
        middlewares: [],
        routers: {},
    },
    "utils": {
        middlewares: [],
        routers: {},
    },
    "metadata-cmp": {
        middlewares: [],
        routers: {
            "/metadata": MetadataCmpMetadataRouter,
            "/metadata/v2": MetadataCmpMetadataV2Router,
            "/metadata/v3": MetadataCmpMetadataV3Router
        },
    },
    "middleware-rest-in-transaction": {
        middlewares: [],
        routers: {},
    },
    "middleware-rest-check-auth": {
        middlewares: [],
        routers: {},
    },
    "query-builder": {
        middlewares: [],
        routers: {},
    },
    "metadata-connector": {
        middlewares: [],
        routers: {
            "/metadata/connectors": MetadataConnectorConnectorsRouter
        },
    },
    "metadata-logic": {
        middlewares: [],
        routers: {},
    },
    "metadata-infoservice-guide": {
        middlewares: [],
        routers: {
            "/metadata/infoserviceguide/fields": MetadataInfoserviceGuideFieldsRouter,
            "/metadata/infoserviceguide/fieldslist": MetadataInfoserviceGuideFieldsListRouter,
            "/metadata/infoserviceguide/indexes": MetadataInfoserviceGuideIndexesRouter,
            "/metadata/infoserviceguide/keys": MetadataInfoserviceGuideKeysRouter,
            "/metadata/infoserviceguide": MetadataInfoserviceGuideInfoservicesRouter
        },
    },
    "metadata-infoservice": {
        middlewares: [],
        routers: {
            "/metadata/infoservice/fields": MetadataInfoserviceFieldsRouter,
            "/metadata/infoservice/fieldslist": MetadataInfoserviceFieldsListRouter,
            "/metadata/infoservice/indexes": MetadataInfoserviceIndexesRouter,
            "/metadata/infoservice/keys": MetadataInfoserviceKeysRouter,
            "/metadata/infoservice/foreignkeys": MetadataInfoserviceForeignKeysRouter,
            "/metadata/infoservice": MetadataInfoserviceInfoservicesRouter
        },
    },
    "meta-aggregate-calc-field": {
        middlewares: [],
        routers: {},
    },
    "meta-where-formatter": {
        middlewares: [],
        routers: {},
    },
    "metadata-processing-query": {
        middlewares: [],
        routers: {},
    },
    "metadata-cubes-query": {
        middlewares: [],
        routers: {},
    },
    "metadata-cubes": {
        middlewares: [],
        routers: {
            "/metadata/cubes/measures/aggregations": MetadataCubesMeasuresAggregationsRouter,
            "/metadata/cubes/fields/aggregations": MetadataCubesFieldsAggregationsRouter,
            "/metadata/cubes/infoservices": MetadataCubesInfoservicesRouter,
            "/metadata/cubes/fields": MetadataCubesFieldsRouter,
            "/metadata/cubes/measures": MetadataCubesMeasuresRouter,
            "/metadata/cubes/dimensions": MetadataCubesDimensionsRouter,
            "/metadata/cubes/fieldslist": MetadataCubesFieldsListRouter,
            "/metadata/cubes/fizfieldslist": MetadataCubesFizFieldsListRouter,
            "/metadata/cubes/infoserviselist": MetadataCubesInfoserviseListRouter,
            "/metadata/cubes/binds": MetadataCubesBindsRouter,
            "/metadata/cubes": MetadataCubesCubesRouter
        },
    },
    "i-l-init": {
        middlewares: [],
        routers: {},
    },
    "i-woke-up": {
        middlewares: [
            IWokeUpIWokeUp
        ],
        routers: {},
    },
    "itable-ext-metadata": {
        middlewares: [],
        routers: {},
    },
    "json-body-ext-rest-express": {
        middlewares: [
            JsonBodyExtRestExpressJsonBody
        ],
        routers: {},
    },
    "logger-mis": {
        middlewares: [
            LoggerMisLoggerMiddleware
        ],
        routers: {},
    },
    "memorysave-ext-helpers": {
        middlewares: [],
        routers: {},
    },
    "memorysave-metadata": {
        middlewares: [],
        routers: {
            "/metadata/cachedmetadata": MemorysaveMetadataMemorySaveMetadataRouter
        },
    },
    "memorysave-storage-node-cache": {
        middlewares: [],
        routers: {},
    },
    "memorysave-storage-redis": {
        middlewares: [],
        routers: {},
    },
    "meta-copy-infofields": {
        middlewares: [],
        routers: {
            "/metadata/metacopyinfofields": MetaCopyInfofieldsMetaCopyInfofieldsRouter
        },
    },
    "meta-copy-paste": {
        middlewares: [],
        routers: {
            "/metadata/metacopypaste": MetaCopyPasteMetaCopyPasteRouter
        },
    },
    "meta-cube-info": {
        middlewares: [],
        routers: {},
    },
    "meta-ddl-dump": {
        middlewares: [],
        routers: {
            "/metaddldump": MetaDdlDumpMetaDDLDumpRouter
        },
    },
    "meta-dumpdb": {
        middlewares: [],
        routers: {
            "/metadata/metadumpdb": MetaDumpdbMetaDumpDBRouter
        },
    },
    "meta-filter": {
        middlewares: [],
        routers: {
            "/metadata/meta-filter": MetaFilterFilterRouter
        },
    },
    "meta-fsck-lib": {
        middlewares: [],
        routers: {},
    },
    "meta-fsck": {
        middlewares: [],
        routers: {
            "/metafsck": MetaFsckMetaFSCKRouter
        },
    },
    "wrapper": {
        middlewares: [],
        routers: {
            "/wrapper": WrapperWrapperRouter
        },
    },
    "meta-new-cube-page": {
        middlewares: [],
        routers: {
            "/metadata/metanewcubepage": MetaNewCubePageMetaNewCubePageRouter,
            "/metadata/metanewreportspage": MetaNewCubePageMetaNewReportPageRouter
        },
    },
    "meta-query-explain": {
        middlewares: [],
        routers: {
            "/metadata/query-explain": MetaQueryExplainMetaQueryExplainRouter
        },
    },
    "meta-search": {
        middlewares: [],
        routers: {
            "/metadata/metasearch": MetaSearchMetaSearchRouter
        },
    },
    "meta-sql-query": {
        middlewares: [],
        routers: {
            "/metasqlquery": MetaSqlQueryMetaSQLQueryRouter
        },
    },
    "meta-synh-dbmodel": {
        middlewares: [],
        routers: {
            "/metadata/metasynhdbmodel": MetaSynhDbmodelMetaSynhDbmodelRouter
        },
    },
    "metadata-enums": {
        middlewares: [],
        routers: {
            "/metadata/enums/values": MetadataEnumsValuesRouter,
            "/metadata/enums": MetadataEnumsEnumsRouter
        },
    },
    "metadata-forms": {
        middlewares: [],
        routers: {
            "/metadata/formsmetadata": MetadataFormsFormsRouter
        },
    },
    "metadata-gp-timeout": {
        middlewares: [],
        routers: {},
    },
    "metadata-cmp-dumps": {
        middlewares: [],
        routers: {},
    },
    "metadata-infoservice-matrixguide": {
        middlewares: [],
        routers: {
            "/metadata/infoservicematrixguide/hierarchy": MetadataInfoserviceMatrixguideHierarchyRouter,
            "/metadata/infoservicematrixguide/sysfields": MetadataInfoserviceMatrixguideSysFieldsRouter,
            "/metadata/infoservicematrixguide/fields": MetadataInfoserviceMatrixguideFieldsRouter,
            "/metadata/infoservicematrixguide/fieldslist": MetadataInfoserviceMatrixguideFieldsListRouter,
            "/metadata/infoservicematrixguide/keys": MetadataInfoserviceMatrixguideKeysRouter,
            "/metadata/infoservicematrixguide": MetadataInfoserviceMatrixguideInfoserviceMatrixGuideRouter
        },
    },
    "metadata-loger": {
        middlewares: [],
        routers: {},
    },
    "metadata-processing": {
        middlewares: [],
        routers: {
            "/metadata/processing/measures/aggregations": MetadataProcessingAggregationsRouter,
            "/metadata/processing/measures": MetadataProcessingMeasuresRouter,
            "/metadata/processing/matrix": MetadataProcessingMatrixRouter,
            "/metadata/processing/dimensions": MetadataProcessingDimensionsRouter,
            "/metadata/processing": MetadataProcessingProcessingRouter,
            "/processing": MetadataProcessingCalculationRouter
        },
    },
    "worker_code": {
        middlewares: [],
        routers: {},
    },
    "metadata-reports": {
        middlewares: [],
        routers: {
            "/metadata/reports/infoservices": MetadataReportsInfoservicesRouter,
            "/metadata/reports/measures": MetadataReportsMeasuresRouter,
            "/metadata/reports/dimensions": MetadataReportsDimensionsRouter,
            "/metadata/reports/infoserviselist": MetadataReportsInfoserviseListRouter,
            "/metadata/reports": MetadataReportsReportsRouter,
            "/metadata/reports/fieldslist": MetadataReportsFieldsListRouter,
            "/metadata/reports/fizfieldslist": MetadataReportsFizFieldsListRouter,
            "/metadata/reports/fields": MetadataReportsFieldsRouter
        },
    },
    "metadata-roles": {
        middlewares: [],
        routers: {
            "/metadata/roles": MetadataRolesRolesRouter
        },
    },
    "metadata-rules": {
        middlewares: [],
        routers: {
            "/metadata/rules": MetadataRulesRulesRouter
        },
    },
    "metadata-users": {
        middlewares: [],
        routers: {
            "/metadata/users": MetadataUsersUsersRouter
        },
    },
    "metadata-rls": {
        middlewares: [],
        routers: {
            "/metadata/rls/condition": MetadataRlsConditionRouter,
            "/metadata/rls": MetadataRlsRlsRouter
        },
    },
    "middleware-rest-cors": {
        middlewares: [],
        routers: {},
    },
    "middleware-rest-decimal": {
        middlewares: [],
        routers: {},
    },
    "middleware-rest-validator": {
        middlewares: [],
        routers: {},
    },
    "rls-core": {
        middlewares: [],
        routers: {
            "/rls": RlsCoreRlsCoreRouter
        },
    },
    "code-manager": {
        middlewares: [],
        routers: {
            "/code": CodeManagerCodeRouter
        },
    },
    "Application": {
        middlewares: [],
        routers: {},
    },
    "meta-object-server-code": {
        middlewares: [],
        routers: {},
    },
    "QueueAgent": {
        middlewares: [],
        routers: {},
    },
    "TransactionAgent": {
        middlewares: [],
        routers: {},
    },
    "metadata-guide": {
        middlewares: [],
        routers: {
            "/metadata/guide/fields": MetadataGuideFieldsRouter,
            "/metadata/guide/fieldslist": MetadataGuideFieldsListRouter,
            "/metadata/guide/tabularparts": MetadataGuideTabularPartsRouter,
            "/metadata/guide/tabularfieldslist": MetadataGuideTabularFieldsListRouter,
            "/metadata/guide/forms": MetadataGuideFormsRouter,
            "/metadata/guide/sysfields": MetadataGuideSysFieldsRouter,
            "/metadata/guide/tabularsysfields": MetadataGuideTabularSysFieldsRouter,
            "/metadata/guide/indexes": MetadataGuideIndexesRouter,
            "/metadata/guide/keys": MetadataGuideKeysRouter,
            "/metadata/guide": MetadataGuideGuideRouter
        },
    },
    "schemas-manager": {
        middlewares: [],
        routers: {
            "/metadata/schemas": SchemasManagerSchemasManagerRouter
        },
    },
    "mis-portal-ext-schemas-manager": {
        middlewares: [],
        routers: {},
    },
    "parse-dbmodel-meta": {
        middlewares: [],
        routers: {
            "/metadata/parsedbmodelmeta": ParseDbmodelMetaParseDbmodelMetaRouter
        },
    },
    "pivot-table": {
        middlewares: [],
        routers: {
            "/pivottables": PivotTablePivotTableRouter
        },
    },
    "reports": {
        middlewares: [],
        routers: {
            "/reports": ReportsReportsRouter
        },
    },
    "reports-xlsx-download": {
        middlewares: [],
        routers: {
            "/metadata/reportsxlsxdownload": ReportsXlsxDownloadReportsXlsxDownloadRouter
        },
    },
    "rest-express": {
        middlewares: [],
        routers: {},
    },
    "rls-ext-metadata": {
        middlewares: [],
        routers: {
            "/rls": RlsExtMetadataRlsExtMetadataRouter
        },
    },
    "rls-ext-metadata-dumps": {
        middlewares: [],
        routers: {},
    },
    "rls-ext-sync": {
        middlewares: [],
        routers: {},
    },
    "rls-ui": {
        middlewares: [],
        routers: {
            "/rls": RlsUiRlsUIRouter
        },
    },
    "session-set": {
        middlewares: [
            SessionSetAppendSessionParser,
            SessionSetCreateMainSession,
            SessionSetCreateUserSession
        ],
        routers: {
            "/session": SessionSetSessionSetRouter
        },
    },
    "store": {
        middlewares: [
            StoreAppendUserData
        ],
        routers: {
            "/users": StoreStoreRouter
        },
    },
    "system-settings": {
        middlewares: [],
        routers: {
            "/systemsettings": SystemSettingsSystemSettingsRouter
        },
    },
    "system-settings-ext-analytics": {
        middlewares: [],
        routers: {},
    },
    "user-device": {
        middlewares: [],
        routers: {
            "/devices": UserDeviceDeviceRouter
        },
    },
    "secman": {
        middlewares: [],
        routers: {},
    },
    "meta-muilti-field": {
        middlewares: [],
        routers: {
            "/metadata/metacompositehelper": MetaMuiltiFieldMetaCompositeHelperRouter
        },
    },
    "postgres-ext-query-builder": {
        middlewares: [],
        routers: {},
    },
    "connector-postgres": {
        middlewares: [],
        routers: {},
    },
    "metadata-forms-dumps": {
        middlewares: [],
        routers: {},
    },
    "metadata-templates-dumps": {
        middlewares: [],
        routers: {},
    },
    "meta-eye": {
        middlewares: [],
        routers: {
            "/metadata/metaeye": MetaEyeMetaEyeRouter
        },
    },
    "meta-matrix": {
        middlewares: [],
        routers: {
            "/metadata/metamatrix": MetaMatrixMetaMatrixRouter
        },
    },
    "template-cms": {
        middlewares: [],
        routers: {
            "/templates": TemplateCmsTemplatesRouter
        },
    },
    "page-cms": {
        middlewares: [],
        routers: {
            "/pages": PageCmsPagesRouter,
            "/dynpage": PageCmsPagesUiRouter
        },
    },
};
