export const PLUGIN_PROFILE_QUERY_KEY = 'PluginProfileQuery' as const;

export const PROFILE_QUERY_ACTION = {
    OPEN: 'PROFILE_QUERY/OPEN',
    CLOSE: 'PROFILE_QUERY/CLOSE',
    ADD_REQUEST: 'PROFILE_QUERY/ADD_REQUEST',
    UPDATE_REQUEST: 'PROFILE_QUERY_UPDATE_REQUEST',
    CLEAR_REQUESTS: 'PROFILE_QUERY/CLEAR_REQUESTS',
} as const;
