/**
 * Autogenerated file. Don't change it manualy.
 */

// ---------------- restmodule: rest-express ----------------
const RestExpress = require("./rest-express");

sreda.restmodule = RestExpress;

sreda.versions = {
    "adminpanel-dumps": "1.5.0",
    "metadata-cmp-dumps": "1.0.1",
    "metadata-cmp": "1.0.0",
    "auth": "1.5.97",
    "metadata-forms": "1.0.0",
    "metadata-roles": "1.5.5",
    "metadata-rules": "1.5.4",
    "metadata-users": "1.5.4",
    "middleware-rest-check-access": "1.5.0",
    "middleware-rest-upload-file": "1.5.1",
    "dump-cms": "1.5.36",
    "i-l-init": "1.0.0",
    "meta-query-explain": "1.0.0",
    "meta-synh-dbmodel": "1.0.0",
    "metadata-connector": "1.0.0",
    "metadata-cubes": "1.0.0",
    "metadata-enums": "1.0.0",
    "metadata-guide": "1.0.0",
    "metadata-infoservice": "1.0.0",
    "metadata-infoservice-matrixguide": "1.0.0",
    "metadata-infoservice-guide": "1.0.0",
    "metadata-processing": "1.0.0",
    "metadata-reports": "1.0.0",
    "metadata-rls": "1.0.0",
    "middleware-rest-check-auth": "1.5.1",
    "middleware-rest-validate": "1.5.0",
    "pivot-table": "1.0.0",
    "rest-express": "1.5.1",
    "rls-core": "1.5.27",
    "rls-ext-metadata": "1.0.0",
    "rls-ext-metadata-dumps": "1.5.0",
    "schemas-manager": "1.0.0",
    "statistic-cube": "1.0.0",
    "store": "1.0.0",
    "system-settings": "1.0.0",
    "system-settings-ext-analytics": "1.0.0",
    "system-settings-dumps": "1.0.18",
    "metadata-forms-dumps": "1.5.0"
};

module.exports = {};
