/**
 * Autogenerated file. Don't change it manualy.
 */

/** -------------------- models -------------------- */

/** metadata-cmp */
const MetadataCmpFamilymetadata = require("./metadata-cmp/db/models/familymetadata");
const MetadataCmpMetadata = require("./metadata-cmp/db/models/metadata");
/** auth */
const AuthGroup = require("./auth/db/models/group");
const AuthGroupuser = require("./auth/db/models/groupuser");
const AuthRolerule = require("./auth/db/models/rolerule");
const AuthUattribute = require("./auth/db/models/uattribute");
const AuthUrole = require("./auth/db/models/urole");
const AuthUrule = require("./auth/db/models/urule");
const AuthUser = require("./auth/db/models/user");
const AuthUserdata = require("./auth/db/models/userdata");
const AuthUserinfo = require("./auth/db/models/userinfo");
const AuthUserrole = require("./auth/db/models/userrole");
const AuthUserrule = require("./auth/db/models/userrule");
/** dump-cms */
const DumpCmsDumpmeta = require("./dump-cms/db/models/dumpmeta");
/** i-l-init */
const ILInitRuntimeConfig = require("./i-l-init/db/models/RuntimeConfig");
/** meta-query-explain */
const MetaQueryExplainExplainRequest = require("./meta-query-explain/db/models/ExplainRequest");
const MetaQueryExplainExplainRequestMeta = require("./meta-query-explain/db/models/ExplainRequestMeta");
/** meta-synh-dbmodel */
const MetaSynhDbmodelMetadatadb = require("./meta-synh-dbmodel/db/models/metadatadb");
/** metadata-processing */
const MetadataProcessingProcessing = require("./metadata-processing/db/models/processing");
/** pivot-table */
const PivotTablePivotSchemas = require("./pivot-table/db/models/PivotSchemas");
/** rls-ext-metadata */
const RlsExtMetadataRlsmetadata = require("./rls-ext-metadata/db/models/rlsmetadata");
/** statistic-cube */
const StatisticCubeCubepriorities = require("./statistic-cube/db/models/cubepriorities");
const StatisticCubeCuberequestpriority = require("./statistic-cube/db/models/cuberequestpriority");
const StatisticCubeCubesrequests = require("./statistic-cube/db/models/cubesrequests");
/** store */
const StoreStore = require("./store/db/models/store");
/** system-settings */
const SystemSettingsSystemSettings = require("./system-settings/db/models/SystemSettings");

module.exports = {
    "adminpanel-dumps": [],
    "metadata-cmp-dumps": [],
    "metadata-cmp": [
        MetadataCmpFamilymetadata,
        MetadataCmpMetadata
    ],
    "auth": [
        AuthGroup,
        AuthGroupuser,
        AuthRolerule,
        AuthUattribute,
        AuthUrole,
        AuthUrule,
        AuthUser,
        AuthUserdata,
        AuthUserinfo,
        AuthUserrole,
        AuthUserrule
    ],
    "metadata-forms": [],
    "metadata-roles": [],
    "metadata-rules": [],
    "metadata-users": [],
    "middleware-rest-check-access": [],
    "middleware-rest-upload-file": [],
    "dump-cms": [
        DumpCmsDumpmeta
    ],
    "i-l-init": [
        ILInitRuntimeConfig
    ],
    "meta-query-explain": [
        MetaQueryExplainExplainRequest,
        MetaQueryExplainExplainRequestMeta
    ],
    "meta-synh-dbmodel": [
        MetaSynhDbmodelMetadatadb
    ],
    "metadata-connector": [],
    "metadata-cubes": [],
    "metadata-enums": [],
    "metadata-guide": [],
    "metadata-infoservice": [],
    "metadata-infoservice-matrixguide": [],
    "metadata-infoservice-guide": [],
    "metadata-processing": [
        MetadataProcessingProcessing
    ],
    "metadata-reports": [],
    "metadata-rls": [],
    "middleware-rest-check-auth": [],
    "middleware-rest-validate": [],
    "pivot-table": [
        PivotTablePivotSchemas
    ],
    "rest-express": [],
    "rls-core": [],
    "rls-ext-metadata": [
        RlsExtMetadataRlsmetadata
    ],
    "rls-ext-metadata-dumps": [],
    "schemas-manager": [],
    "statistic-cube": [
        StatisticCubeCubepriorities,
        StatisticCubeCuberequestpriority,
        StatisticCubeCubesrequests
    ],
    "store": [
        StoreStore
    ],
    "system-settings": [
        SystemSettingsSystemSettings
    ],
    "system-settings-ext-analytics": [],
    "system-settings-dumps": [],
    "metadata-forms-dumps": [],
};
