/**
 * Autogenerated file. Don't change it manualy.
 */

/** dump-cms */
const DumpCmsDumpDBRouter = require("./dump-cms/routers/DumpDB.router");
/** rls-core */
const RlsCoreRlsCoreRouter = require("./rls-core/routers/RlsCore.router");

module.exports = {
    "adminpanel-dumps": {
        middlewares: [],
        routers: {},
    },
    "metadata-cmp-dumps": {
        middlewares: [],
        routers: {},
    },
    "metadata-cmp": {
        middlewares: [],
        routers: {},
    },
    "auth": {
        middlewares: [],
        routers: {},
    },
    "metadata-forms": {
        middlewares: [],
        routers: {},
    },
    "metadata-roles": {
        middlewares: [],
        routers: {},
    },
    "metadata-rules": {
        middlewares: [],
        routers: {},
    },
    "metadata-users": {
        middlewares: [],
        routers: {},
    },
    "middleware-rest-check-access": {
        middlewares: [],
        routers: {},
    },
    "middleware-rest-upload-file": {
        middlewares: [],
        routers: {},
    },
    "dump-cms": {
        middlewares: [],
        routers: {
            "/dumpdb": DumpCmsDumpDBRouter
        },
    },
    "i-l-init": {
        middlewares: [],
        routers: {},
    },
    "meta-query-explain": {
        middlewares: [],
        routers: {},
    },
    "meta-synh-dbmodel": {
        middlewares: [],
        routers: {},
    },
    "metadata-connector": {
        middlewares: [],
        routers: {},
    },
    "metadata-cubes": {
        middlewares: [],
        routers: {},
    },
    "metadata-enums": {
        middlewares: [],
        routers: {},
    },
    "metadata-guide": {
        middlewares: [],
        routers: {},
    },
    "metadata-infoservice": {
        middlewares: [],
        routers: {},
    },
    "metadata-infoservice-matrixguide": {
        middlewares: [],
        routers: {},
    },
    "metadata-infoservice-guide": {
        middlewares: [],
        routers: {},
    },
    "metadata-processing": {
        middlewares: [],
        routers: {},
    },
    "metadata-reports": {
        middlewares: [],
        routers: {},
    },
    "metadata-rls": {
        middlewares: [],
        routers: {},
    },
    "middleware-rest-check-auth": {
        middlewares: [],
        routers: {},
    },
    "middleware-rest-validate": {
        middlewares: [],
        routers: {},
    },
    "pivot-table": {
        middlewares: [],
        routers: {},
    },
    "rest-express": {
        middlewares: [],
        routers: {},
    },
    "rls-core": {
        middlewares: [],
        routers: {
            "/rls": RlsCoreRlsCoreRouter
        },
    },
    "rls-ext-metadata": {
        middlewares: [],
        routers: {},
    },
    "rls-ext-metadata-dumps": {
        middlewares: [],
        routers: {},
    },
    "schemas-manager": {
        middlewares: [],
        routers: {},
    },
    "statistic-cube": {
        middlewares: [],
        routers: {},
    },
    "store": {
        middlewares: [],
        routers: {},
    },
    "system-settings": {
        middlewares: [],
        routers: {},
    },
    "system-settings-ext-analytics": {
        middlewares: [],
        routers: {},
    },
    "system-settings-dumps": {
        middlewares: [],
        routers: {},
    },
    "metadata-forms-dumps": {
        middlewares: [],
        routers: {},
    },
};
