/**
 * Autogenerated file. Don't change it manualy.
 */

/** -------------------- services -------------------- */

/** middleware-rest-check-access */
const MiddlewareRestCheckAccessCheckAccess = require("./middleware-rest-check-access/services/checkAccess");
/** middleware-rest-upload-file */
const MiddlewareRestUploadFileStorageDiskStorage = require("./middleware-rest-upload-file/services/storage/Disk.storage");
const MiddlewareRestUploadFileStorageRedisStorage = require("./middleware-rest-upload-file/services/storage/Redis.storage");
const MiddlewareRestUploadFileUploadFile = require("./middleware-rest-upload-file/services/uploadFile");
/** dump-cms */
const DumpCmsDumpDBService = require("./dump-cms/services/DumpDB.service");
const DumpCmsModelDumpBDModel = require("./dump-cms/services/model/DumpBD.model");
/** middleware-rest-check-auth */
const MiddlewareRestCheckAuthCheckAuth = require("./middleware-rest-check-auth/services/checkAuth");
/** middleware-rest-validate */
const MiddlewareRestValidateValidateMiddleware = require("./middleware-rest-validate/services/validateMiddleware");
/** rls-core */
const RlsCoreModelsRlsCoreModel = require("./rls-core/services/models/RlsCore.model");
const RlsCoreRlsCoreService = require("./rls-core/services/RlsCore.service");

module.exports = {
    "adminpanel-dumps": {
        services: {},
        hooks: {},
    },
    "metadata-cmp-dumps": {
        services: {},
        hooks: {},
    },
    "metadata-cmp": {
        services: {},
        hooks: {},
    },
    "auth": {
        services: {},
        hooks: {},
    },
    "metadata-forms": {
        services: {},
        hooks: {},
    },
    "metadata-roles": {
        services: {},
        hooks: {},
    },
    "metadata-rules": {
        services: {},
        hooks: {},
    },
    "metadata-users": {
        services: {},
        hooks: {},
    },
    "middleware-rest-check-access": {
        services: {
            CheckAccess: MiddlewareRestCheckAccessCheckAccess
        },
        hooks: {},
    },
    "middleware-rest-upload-file": {
        services: {
            StorageDiskStorage: MiddlewareRestUploadFileStorageDiskStorage,
            StorageRedisStorage: MiddlewareRestUploadFileStorageRedisStorage,
            UploadFile: MiddlewareRestUploadFileUploadFile
        },
        hooks: {},
    },
    "dump-cms": {
        services: {
            DumpDBService: DumpCmsDumpDBService,
            ModelDumpBDModel: DumpCmsModelDumpBDModel
        },
        hooks: {},
    },
    "i-l-init": {
        services: {},
        hooks: {},
    },
    "meta-query-explain": {
        services: {},
        hooks: {},
    },
    "meta-synh-dbmodel": {
        services: {},
        hooks: {},
    },
    "metadata-connector": {
        services: {},
        hooks: {},
    },
    "metadata-cubes": {
        services: {},
        hooks: {},
    },
    "metadata-enums": {
        services: {},
        hooks: {},
    },
    "metadata-guide": {
        services: {},
        hooks: {},
    },
    "metadata-infoservice": {
        services: {},
        hooks: {},
    },
    "metadata-infoservice-matrixguide": {
        services: {},
        hooks: {},
    },
    "metadata-infoservice-guide": {
        services: {},
        hooks: {},
    },
    "metadata-processing": {
        services: {},
        hooks: {},
    },
    "metadata-reports": {
        services: {},
        hooks: {},
    },
    "metadata-rls": {
        services: {},
        hooks: {},
    },
    "middleware-rest-check-auth": {
        services: {
            CheckAuth: MiddlewareRestCheckAuthCheckAuth
        },
        hooks: {},
    },
    "middleware-rest-validate": {
        services: {
            ValidateMiddleware: MiddlewareRestValidateValidateMiddleware
        },
        hooks: {},
    },
    "pivot-table": {
        services: {},
        hooks: {},
    },
    "rest-express": {
        services: {},
        hooks: {},
    },
    "rls-core": {
        services: {
            ModelsRlsCoreModel: RlsCoreModelsRlsCoreModel,
            RlsCoreService: RlsCoreRlsCoreService
        },
        hooks: {},
    },
    "rls-ext-metadata": {
        services: {},
        hooks: {},
    },
    "rls-ext-metadata-dumps": {
        services: {},
        hooks: {},
    },
    "schemas-manager": {
        services: {},
        hooks: {},
    },
    "statistic-cube": {
        services: {},
        hooks: {},
    },
    "store": {
        services: {},
        hooks: {},
    },
    "system-settings": {
        services: {},
        hooks: {},
    },
    "system-settings-ext-analytics": {
        services: {},
        hooks: {},
    },
    "system-settings-dumps": {
        services: {},
        hooks: {},
    },
    "metadata-forms-dumps": {
        services: {},
        hooks: {},
    },
};
