const config = {
    development: {
        username: process.env.DB_USER,
        password: process.env.DB_PASS,
        database: process.env.DB_DATABASE,
        host: process.env.DB_HOST,
        port: process.env.DB_PORT,
        schema: process.env.DB_SCHEMA,
        dialect: process.env.DB_DIALECT,
        patroni: sreda.env?.DB_PATRONI ?? process.env.DB_PATRONI,
        pool: sreda.env?.DB_POOL ?? { max: 100, min: 0, idle: 1000 },
        logging: console.debug,
        ca: process.env?.DB_SSL_CA,
        key: process.env.DB_SSL_KEY,
        cert: process.env?.DB_SSL_CERT,
        // dialectModule: 'pg',
    },
    psi: {
        username: process.env.DB_USER,
        password: process.env.DB_PASS,
        database: process.env.DB_DATABASE,
        host: process.env.DB_HOST,
        port: process.env.DB_PORT,
        schema: process.env.DB_SCHEMA,
        dialect: process.env.DB_DIALECT,
        patroni: sreda.env?.DB_PATRONI ?? process.env.DB_PATRONI,
        pool: sreda.env?.DB_POOL ?? { max: 100, min: 0, idle: 1000 },
        logging: console.debug,
        ca: process.env?.DB_SSL_CA,
        key: process.env.DB_SSL_KEY,
        cert: process.env?.DB_SSL_CERT,
    },
    test: {
        username: process.env.DB_USER,
        password: process.env.DB_PASS,
        database: process.env.DB_TEST_DATABASE,
        host: process.env.DB_HOST,
        port: process.env.DB_PORT,
        schema: process.env.DB_SCHEMA,
        dialect: process.env.DB_DIALECT,
        patroni: sreda.env?.DB_PATRONI ?? process.env.DB_PATRONI,
        pool: sreda.env?.DB_POOL ?? { max: 100, min: 0, idle: 1000 },
        logging: console.debug,
        ca: process.env?.DB_SSL_CA,
        key: process.env.DB_SSL_KEY,
        cert: process.env?.DB_SSL_CERT,
    },
    production: {
        username: process.env.DB_USER,
        password: process.env.DB_PASS,
        database: process.env.DB_DATABASE,
        host: process.env.DB_HOST,
        port: process.env.DB_PORT,
        schema: process.env.DB_SCHEMA,
        dialect: process.env.DB_DIALECT,
        patroni: sreda.env?.DB_PATRONI ?? process.env.DB_PATRONI,
        pool: sreda.env?.DB_POOL ?? { max: 100, min: 0, idle: 1000 },
        logging: console.debug,
        ca: process.env?.DB_SSL_CA,
        key: process.env.DB_SSL_KEY,
        cert: process.env?.DB_SSL_CERT,
    },
};

module.exports = config[sreda.env.NODE_ENV];
